version: '3'

services:
  app:
    build:
      context: app
    ports:
      - '5000'

  api:
    build:
      context: api
    ports:
      - '5001'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - api
    ports:
      - '80:80'
