version: '3'

services:
  py:
    build:
      context: py
    ports:
      - '5000'

  js:
    build:
      context: js
    ports:
      - '5001'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html:ro
    depends_on:
      - py
      - js
    ports:
      - '80:80'
